# Meta Data for SEO

## Homepage
title = "Sciri.net"
titleSeparator = "—"
titleAddition = "Sean Sosik-Hamor's Knowledge Base and Projects"
description = "Sean has way too many interests and hobbies, and has left his footprints all over the net. Sciri.net is his knowledge base and index of personal, professional, and family projects."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "sciri.net"
titleHome = "Sean Sosik-Hamor's Knowledge Base and Projects"

## Twitter Cards
twitterSite = "@Sciri"
twitterCreator = "@Sciri"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Sciri"
schemaAuthor = "Sean Sosik-Hamor"
schemaAuthorTwitter = "https://twitter.com/Sciri"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/sosikhamor/"
schemaAuthorGitHub = "https://github.com/SeanSosikHamor"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/Sciri"
schemaLinkedIn = "https://www.linkedin.com/in/sosikhamor/"
schemaGitHub = "https://github.com/SeanSosikHamor"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Copyright &copy; 2008–2023 Sean Sosik-Hamor. All Rights Reserved."

# Feed
copyRight = "Copyright &copy; 2008–2023 Sean Sosik-Hamor. All Rights Reserved."

# Alert
alert = false
alertDismissable = true
# alertText = "Alert 1"
alertText = "Alert 2"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/SeanSosikHamor/Website-Sciri.net-hugo-doks"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
